#!/bin/bash 

qemu-system-arm -M versatilepb -kernel ./vmlinuz-2.6.26-2-versatile -initrd ./initrd.img-2.6.26-2-versatile -hda ./armdisk.img -append "root=/dev/sda1" -net nic -net tap,ifname=tap0,script=no
