CREATE DATABASE logs;
GRANT ALL PRIVILEGES ON logs.* TO 'logmgr' IDENTIFIED BY 'logpass'; FLUSH PRIVILEGES;
DROP TABLE  `logs`.`LOGS` ;
DROP TABLE  `logs`.`LOG_SOURCES` ;


CREATE TABLE `logs`.`LOG_SOURCES` (
  `SOURCE_ID` INT  NOT NULL AUTO_INCREMENT,
  `SOURCE_DESCRIPTION` VARCHAR(128)  NOT NULL,
  `DISCARD_LEVEL` INT  NOT NULL DEFAULT 2,
  PRIMARY KEY (`SOURCE_ID`, `SOURCE_DESCRIPTION`)
)
ENGINE = InnoDB;

CREATE TABLE `logs`.`LOGS` (
  `LOG_ID` INT  NOT NULL AUTO_INCREMENT,
  `AUTO_TIMESTAMP` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `LEVEL` INT  NOT NULL,
  `SOURCE_ID` INT  NOT NULL,
  `TIMESTAMP` DOUBLE  NOT NULL,
  `METHOD` VARCHAR(256),
  `LINE_NUMBER` INT NOT NULL DEFAULT -1,
  `DATA` VARCHAR(2048) ,
  PRIMARY KEY (`LOG_ID`),
  CONSTRAINT `sourceid_fk_constraint` FOREIGN KEY `sourceid_fk_constraint` (`SOURCE_ID`)
    REFERENCES `LOG_SOURCES` (`SOURCE_ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT
)
ENGINE = InnoDB;

