// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `LogPublisher.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <LogPublisher.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __Log__LogPublisher__logEvent_name = "logEvent";

::Ice::Object* IceInternal::upCast(::Log::LogPublisher* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::Log::LogPublisher* p) { return p; }

void
Log::__read(::IceInternal::BasicStream* __is, ::Log::LogPublisherPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Log::LogPublisher;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Log::LogPublisher::logEvent(const ::Log::LogMessageData& log, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Log::LogPublisher* __del = dynamic_cast< ::IceDelegate::Log::LogPublisher*>(__delBase.get());
            __del->logEvent(log, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Log::LogPublisher::begin_logEvent(const ::Log::LogMessageData& log, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Log__LogPublisher__logEvent_name, __del, __cookie);
    try
    {
        __result->__prepare(__Log__LogPublisher__logEvent_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        log.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Log::LogPublisher::end_logEvent(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Log__LogPublisher__logEvent_name);
}

const ::std::string&
IceProxy::Log::LogPublisher::ice_staticId()
{
    return ::Log::LogPublisher::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Log::LogPublisher::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Log::LogPublisher);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Log::LogPublisher::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Log::LogPublisher);
}

::IceProxy::Ice::Object*
IceProxy::Log::LogPublisher::__newInstance() const
{
    return new LogPublisher;
}

void
IceDelegateM::Log::LogPublisher::logEvent(const ::Log::LogMessageData& log, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Log__LogPublisher__logEvent_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        log.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateD::Log::LogPublisher::logEvent(const ::Log::LogMessageData& log, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Log::LogMessageData& log, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_log(log)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Log::LogPublisher* servant = dynamic_cast< ::Log::LogPublisher*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->logEvent(_m_log, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Log::LogMessageData& _m_log;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Log__LogPublisher__logEvent_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(log, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::ObjectPtr
Log::LogPublisher::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __Log__LogPublisher_ids[2] =
{
    "::Ice::Object",
    "::Log::LogPublisher"
};

bool
Log::LogPublisher::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Log__LogPublisher_ids, __Log__LogPublisher_ids + 2, _s);
}

::std::vector< ::std::string>
Log::LogPublisher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Log__LogPublisher_ids[0], &__Log__LogPublisher_ids[2]);
}

const ::std::string&
Log::LogPublisher::ice_id(const ::Ice::Current&) const
{
    return __Log__LogPublisher_ids[1];
}

const ::std::string&
Log::LogPublisher::ice_staticId()
{
    return __Log__LogPublisher_ids[1];
}

::Ice::DispatchStatus
Log::LogPublisher::___logEvent(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Log::LogMessageData log;
    log.__read(__is);
    __is->endReadEncaps();
    logEvent(log, __current);
    return ::Ice::DispatchOK;
}

static ::std::string __Log__LogPublisher_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "logEvent"
};

::Ice::DispatchStatus
Log::LogPublisher::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__Log__LogPublisher_all, __Log__LogPublisher_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Log__LogPublisher_all)
    {
        case 0:
        {
            return ___ice_id(in, current);
        }
        case 1:
        {
            return ___ice_ids(in, current);
        }
        case 2:
        {
            return ___ice_isA(in, current);
        }
        case 3:
        {
            return ___ice_ping(in, current);
        }
        case 4:
        {
            return ___logEvent(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Log::LogPublisher::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
Log::LogPublisher::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
Log::LogPublisher::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Log::LogPublisher was not generated with stream support";
    throw ex;
}

void
Log::LogPublisher::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Log::LogPublisher was not generated with stream support";
    throw ex;
}
#endif

void 
Log::__patch__LogPublisherPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::Log::LogPublisherPtr* p = static_cast< ::Log::LogPublisherPtr*>(__addr);
    assert(p);
    *p = ::Log::LogPublisherPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::Log::LogPublisher::ice_staticId(), v->ice_id());
    }
}
