install:
	@echo "Copying /eso50cm/config/ files"
	@cp ../eso50cm/config/* /eso50cm/config
	@echo "Copying /eso50/bin scripts"
	@cp ../eso50cm/bin/* /eso50cm/bin
	@echo "Creating /eso50cm/SWROOT/db if it doesn't exist" 
	@mkdir -p /eso50cm/SWROOT/db
	@echo "Done"
