// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Logger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Logger.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __Log__Logger__logMessage_name = "logMessage";

static const ::std::string __Log__Logger__setDiscardLevel_name = "setDiscardLevel";

static const ::std::string __Log__Logger__getDiscardLevel_name = "getDiscardLevel";

::Ice::Object* IceInternal::upCast(::Log::Logger* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::Log::Logger* p) { return p; }

void
Log::__read(::IceInternal::BasicStream* __is, ::Log::LoggerPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::Log::Logger;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::Log::Logger::logMessage(const ::Log::LogMessageData& log, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Log::Logger* __del = dynamic_cast< ::IceDelegate::Log::Logger*>(__delBase.get());
            __del->logMessage(log, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Log::Logger::begin_logMessage(const ::Log::LogMessageData& log, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Log__Logger__logMessage_name, __del, __cookie);
    try
    {
        __result->__prepare(__Log__Logger__logMessage_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        log.__write(__os);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Log::Logger::end_logMessage(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Log__Logger__logMessage_name);
}

void
IceProxy::Log::Logger::setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::Log::Logger* __del = dynamic_cast< ::IceDelegate::Log::Logger*>(__delBase.get());
            __del->setDiscardLevel(source, level, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapperRelaxed(__delBase, __ex, true, __cnt);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Log::Logger::begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Log__Logger__setDiscardLevel_name, __del, __cookie);
    try
    {
        __result->__prepare(__Log__Logger__setDiscardLevel_name, ::Ice::Idempotent, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(source);
        ::Log::__write(__os, level);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::Log::Logger::end_setDiscardLevel(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __Log__Logger__setDiscardLevel_name);
}

::Ice::Int
IceProxy::Log::Logger::getDiscardLevel(const ::std::string& source, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__Log__Logger__getDiscardLevel_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::Log::Logger* __del = dynamic_cast< ::IceDelegate::Log::Logger*>(__delBase.get());
            return __del->getDiscardLevel(source, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::Log::Logger::begin_getDiscardLevel(const ::std::string& source, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__Log__Logger__getDiscardLevel_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __Log__Logger__getDiscardLevel_name, __del, __cookie);
    try
    {
        __result->__prepare(__Log__Logger__getDiscardLevel_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(source);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::Ice::Int
IceProxy::Log::Logger::end_getDiscardLevel(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __Log__Logger__getDiscardLevel_name);
    ::Ice::Int __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::Log::Logger::ice_staticId()
{
    return ::Log::Logger::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::Log::Logger::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::Log::Logger);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::Log::Logger::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::Log::Logger);
}

::IceProxy::Ice::Object*
IceProxy::Log::Logger::__newInstance() const
{
    return new Logger;
}

void
IceDelegateM::Log::Logger::logMessage(const ::Log::LogMessageData& log, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Log__Logger__logMessage_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        log.__write(__os);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::Log::Logger::setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Log__Logger__setDiscardLevel_name, ::Ice::Idempotent, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(source);
        ::Log::__write(__os, level);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::Ice::Int
IceDelegateM::Log::Logger::getDiscardLevel(const ::std::string& source, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __Log__Logger__getDiscardLevel_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(source);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::Ice::Int __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::Log::Logger::logMessage(const ::Log::LogMessageData& log, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::Log::LogMessageData& log, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_log(log)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Log::Logger* servant = dynamic_cast< ::Log::Logger*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->logMessage(_m_log, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::Log::LogMessageData& _m_log;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Log__Logger__logMessage_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(log, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::Log::Logger::setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_source(source),
            _m_level(level)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Log::Logger* servant = dynamic_cast< ::Log::Logger*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->setDiscardLevel(_m_source, _m_level, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_source;
        ::Log::LogLevel _m_level;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Log__Logger__setDiscardLevel_name, ::Ice::Idempotent, __context);
    try
    {
        _DirectI __direct(source, level, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::Ice::Int
IceDelegateD::Log::Logger::getDiscardLevel(const ::std::string& source, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Int& __result, const ::std::string& source, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_source(source)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::Log::Logger* servant = dynamic_cast< ::Log::Logger*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getDiscardLevel(_m_source, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Int& _result;
        const ::std::string& _m_source;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __Log__Logger__getDiscardLevel_name, ::Ice::Normal, __context);
    ::Ice::Int __result;
    try
    {
        _DirectI __direct(__result, source, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
Log::Logger::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __Log__Logger_ids[2] =
{
    "::Ice::Object",
    "::Log::Logger"
};

bool
Log::Logger::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__Log__Logger_ids, __Log__Logger_ids + 2, _s);
}

::std::vector< ::std::string>
Log::Logger::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__Log__Logger_ids[0], &__Log__Logger_ids[2]);
}

const ::std::string&
Log::Logger::ice_id(const ::Ice::Current&) const
{
    return __Log__Logger_ids[1];
}

const ::std::string&
Log::Logger::ice_staticId()
{
    return __Log__Logger_ids[1];
}

::Ice::DispatchStatus
Log::Logger::___logMessage(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::Log::LogMessageData log;
    log.__read(__is);
    __is->endReadEncaps();
    logMessage(log, __current);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Log::Logger::___setDiscardLevel(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Idempotent, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string source;
    ::Log::LogLevel level;
    __is->read(source);
    ::Log::__read(__is, level);
    __is->endReadEncaps();
    setDiscardLevel(source, level, __current);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
Log::Logger::___getDiscardLevel(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string source;
    __is->read(source);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::Ice::Int __ret = getDiscardLevel(source, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __Log__Logger_all[] =
{
    "getDiscardLevel",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "logMessage",
    "setDiscardLevel"
};

::Ice::DispatchStatus
Log::Logger::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__Log__Logger_all, __Log__Logger_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __Log__Logger_all)
    {
        case 0:
        {
            return ___getDiscardLevel(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___logMessage(in, current);
        }
        case 6:
        {
            return ___setDiscardLevel(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
Log::Logger::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
Log::Logger::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
Log::Logger::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Log::Logger was not generated with stream support";
    throw ex;
}

void
Log::Logger::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type Log::Logger was not generated with stream support";
    throw ex;
}
#endif

void 
Log::__patch__LoggerPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::Log::LoggerPtr* p = static_cast< ::Log::LoggerPtr*>(__addr);
    assert(p);
    *p = ::Log::LoggerPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::Log::Logger::ice_staticId(), v->ice_id());
    }
}
