// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Logger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ___home_tcsmgr_CURRENTLY_MOD_eso50cm_ESO50CM_Logger_src_Logger_h__
#define ___home_tcsmgr_CURRENTLY_MOD_eso50cm_ESO50CM_Logger_src_Logger_h__

#include <Ice/LocalObjectF.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <Ice/FactoryTableInit.h>
#include <IceUtil/ScopedArray.h>
#include <Ice/StreamF.h>
#include <LogMessage.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace Log
{

class Logger;

}

}

namespace Log
{

class Logger;
bool operator==(const Logger&, const Logger&);
bool operator<(const Logger&, const Logger&);

}

namespace IceInternal
{

::Ice::Object* upCast(::Log::Logger*);
::IceProxy::Ice::Object* upCast(::IceProxy::Log::Logger*);

}

namespace Log
{

typedef ::IceInternal::Handle< ::Log::Logger> LoggerPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::Log::Logger> LoggerPrx;

void __read(::IceInternal::BasicStream*, LoggerPrx&);
void __patch__LoggerPtr(void*, ::Ice::ObjectPtr&);

}

namespace Log
{

class Callback_Logger_logMessage_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Logger_logMessage_Base> Callback_Logger_logMessagePtr;

class Callback_Logger_setDiscardLevel_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Logger_setDiscardLevel_Base> Callback_Logger_setDiscardLevelPtr;

class Callback_Logger_getDiscardLevel_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_Logger_getDiscardLevel_Base> Callback_Logger_getDiscardLevelPtr;

}

namespace IceProxy
{

namespace Log
{

class Logger : virtual public ::IceProxy::Ice::Object
{
public:

    void logMessage(const ::Log::LogMessageData& log)
    {
        logMessage(log, 0);
    }
    void logMessage(const ::Log::LogMessageData& log, const ::Ice::Context& __ctx)
    {
        logMessage(log, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log)
    {
        return begin_logMessage(log, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log, const ::Ice::Context& __ctx)
    {
        return begin_logMessage(log, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_logMessage(log, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_logMessage(log, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log, const ::Log::Callback_Logger_logMessagePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_logMessage(log, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData& log, const ::Ice::Context& __ctx, const ::Log::Callback_Logger_logMessagePtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_logMessage(log, &__ctx, __del, __cookie);
    }

    void end_logMessage(const ::Ice::AsyncResultPtr&);
    
private:

    void logMessage(const ::Log::LogMessageData&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_logMessage(const ::Log::LogMessageData&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void setDiscardLevel(const ::std::string& source, ::Log::LogLevel level)
    {
        setDiscardLevel(source, level, 0);
    }
    void setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context& __ctx)
    {
        setDiscardLevel(source, level, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level)
    {
        return begin_setDiscardLevel(source, level, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context& __ctx)
    {
        return begin_setDiscardLevel(source, level, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setDiscardLevel(source, level, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setDiscardLevel(source, level, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Log::Callback_Logger_setDiscardLevelPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setDiscardLevel(source, level, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string& source, ::Log::LogLevel level, const ::Ice::Context& __ctx, const ::Log::Callback_Logger_setDiscardLevelPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_setDiscardLevel(source, level, &__ctx, __del, __cookie);
    }

    void end_setDiscardLevel(const ::Ice::AsyncResultPtr&);
    
private:

    void setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    ::Ice::Int getDiscardLevel(const ::std::string& source)
    {
        return getDiscardLevel(source, 0);
    }
    ::Ice::Int getDiscardLevel(const ::std::string& source, const ::Ice::Context& __ctx)
    {
        return getDiscardLevel(source, &__ctx);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source)
    {
        return begin_getDiscardLevel(source, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source, const ::Ice::Context& __ctx)
    {
        return begin_getDiscardLevel(source, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDiscardLevel(source, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDiscardLevel(source, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source, const ::Log::Callback_Logger_getDiscardLevelPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDiscardLevel(source, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string& source, const ::Ice::Context& __ctx, const ::Log::Callback_Logger_getDiscardLevelPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getDiscardLevel(source, &__ctx, __del, __cookie);
    }

    ::Ice::Int end_getDiscardLevel(const ::Ice::AsyncResultPtr&);
    
private:

    ::Ice::Int getDiscardLevel(const ::std::string&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getDiscardLevel(const ::std::string&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<Logger> ice_context(const ::Ice::Context& __context) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_context(__context).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_context(__context).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_adapterId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_adapterId(__id).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_endpoints(__endpoints).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_locatorCacheTimeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_locatorCacheTimeout(__timeout).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_connectionCached(bool __cached) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_connectionCached(__cached).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_endpointSelection(__est).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_secure(bool __secure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_secure(__secure).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_preferSecure(bool __preferSecure) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_preferSecure(__preferSecure).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_router(const ::Ice::RouterPrx& __router) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_router(__router).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_router(__router).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_locator(__locator).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_collocationOptimized(bool __co) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_collocationOptimized(__co).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_twoway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_twoway().get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_twoway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_oneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_oneway().get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_oneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_batchOneway() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_batchOneway().get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_datagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_datagram().get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_datagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_batchDatagram() const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_batchDatagram().get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_compress(bool __compress) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_compress(__compress).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_timeout(int __timeout) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_timeout(__timeout).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    #endif
    }
    
    ::IceInternal::ProxyHandle<Logger> ice_connectionId(const std::string& __id) const
    {
    #if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
        typedef ::IceProxy::Ice::Object _Base;
        return dynamic_cast<Logger*>(_Base::ice_connectionId(__id).get());
    #else
        return dynamic_cast<Logger*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    #endif
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace Log
{

class Logger : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void logMessage(const ::Log::LogMessageData&, const ::Ice::Context*) = 0;

    virtual void setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Context*) = 0;

    virtual ::Ice::Int getDiscardLevel(const ::std::string&, const ::Ice::Context*) = 0;
};

}

}

namespace IceDelegateM
{

namespace Log
{

class Logger : virtual public ::IceDelegate::Log::Logger,
               virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void logMessage(const ::Log::LogMessageData&, const ::Ice::Context*);

    virtual void setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Context*);

    virtual ::Ice::Int getDiscardLevel(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace IceDelegateD
{

namespace Log
{

class Logger : virtual public ::IceDelegate::Log::Logger,
               virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void logMessage(const ::Log::LogMessageData&, const ::Ice::Context*);

    virtual void setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Context*);

    virtual ::Ice::Int getDiscardLevel(const ::std::string&, const ::Ice::Context*);
};

}

}

namespace Log
{

class Logger : virtual public ::Ice::Object
{
public:

    typedef LoggerPrx ProxyType;
    typedef LoggerPtr PointerType;
    
    virtual ::Ice::ObjectPtr ice_clone() const;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void logMessage(const ::Log::LogMessageData&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___logMessage(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void setDiscardLevel(const ::std::string&, ::Log::LogLevel, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___setDiscardLevel(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::Int getDiscardLevel(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getDiscardLevel(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void __write(::IceInternal::BasicStream*) const;
    virtual void __read(::IceInternal::BasicStream*, bool);
// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
    virtual void __write(const ::Ice::OutputStreamPtr&) const;
    virtual void __read(const ::Ice::InputStreamPtr&, bool);
#endif
};

inline bool operator==(const Logger& l, const Logger& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const Logger& l, const Logger& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace Log
{

template<class T>
class CallbackNC_Logger_logMessage : public Callback_Logger_logMessage_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Logger_logMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_logMessage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_logMessage<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_logMessage<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_logMessage<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Logger_logMessage : public Callback_Logger_logMessage_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Logger_logMessage(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_logMessage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_logMessage<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_logMessage<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_logMessagePtr
newCallback_Logger_logMessage(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_logMessage<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Logger_setDiscardLevel : public Callback_Logger_setDiscardLevel_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_Logger_setDiscardLevel(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_setDiscardLevel<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_setDiscardLevel<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_setDiscardLevel<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_setDiscardLevel<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_Logger_setDiscardLevel : public Callback_Logger_setDiscardLevel_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_Logger_setDiscardLevel(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_setDiscardLevel<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_setDiscardLevel<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_setDiscardLevel<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_setDiscardLevelPtr
newCallback_Logger_setDiscardLevel(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_setDiscardLevel<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_Logger_getDiscardLevel : public Callback_Logger_getDiscardLevel_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(::Ice::Int);

    CallbackNC_Logger_getDiscardLevel(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Log::LoggerPrx __proxy = ::Log::LoggerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getDiscardLevel(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret);
#else
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
#endif
        }
    }

    Response response;
};

template<class T> Callback_Logger_getDiscardLevelPtr
newCallback_Logger_getDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_getDiscardLevel<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_Logger_getDiscardLevelPtr
newCallback_Logger_getDiscardLevel(T* instance, void (T::*cb)(::Ice::Int), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_Logger_getDiscardLevel<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_Logger_getDiscardLevel : public Callback_Logger_getDiscardLevel_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(::Ice::Int, const CT&);

    Callback_Logger_getDiscardLevel(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::Log::LoggerPrx __proxy = ::Log::LoggerPrx::uncheckedCast(__result->getProxy());
        ::Ice::Int __ret;
        try
        {
            __ret = __proxy->end_getDiscardLevel(__result);
        }
        catch(::Ice::Exception& ex)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            __exception(__result, ex);
#else
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
#endif
            return;
        }
        if(response)
        {
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
            (callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#else
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
#endif
        }
    }

    Response response;
};

template<class T, typename CT> Callback_Logger_getDiscardLevelPtr
newCallback_Logger_getDiscardLevel(const IceUtil::Handle<T>& instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_getDiscardLevel<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_Logger_getDiscardLevelPtr
newCallback_Logger_getDiscardLevel(T* instance, void (T::*cb)(::Ice::Int, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_Logger_getDiscardLevel<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
